---
- name: Pre Tasks
  hosts: "{{ service }}"
  gather_facts: false
  pre_tasks:
    - local_action: wait_for port=22 host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %}
    - raw: sudo bash -c "sudo test -e /usr/bin/python || (sudo apt -qqy update && sudo apt install -qy python python3)"
    - setup:

- name: "Deploy {{ service }}"
  hosts:  "{{ service }}"
  roles:
    - { role: roles/common, become: true }
    - { role: "roles/{{ service }}", become: true }